<?php
/**
 * Created by PhpStorm.
 * User: gsj
 * Date: 2020/7/20
 * Time: 17:32
 */

namespace App\Admin\Actions;

use Dcat\Admin\Grid\RowAction;

class ReduceCount extends RowAction
{
    public function title()
    {
        return '减少数量';
    }
    public function script()
    {
        $id =$this->row->id;

        return <<<JS

$(".reduce-count-{$id}").on('click', function () {
        var id = $id;
          var count = $(".add-count-{$id}").parents("tr").children("td").eq(6).text();
          var count_a = parseInt(count);
          var count_add = count_a - 1;
          $(".add-count-{$id}").parents("tr").children("td").eq(6).text(count_add);
          $.ajax({
                type: 'POST',
                url: '../admin/shopping/reduce/' + id,
                data: {'_token':'{{csrf_token()}}'},
                success: function (resp) {
                   Dcat.success('数量减少', null, {
    timeOut: 5000, // 5秒后自动消失
});
                },
                error: function (resp) {
                alert(resp.responseText)
                },
            });
    console.log($(this).data('id'));
    console.log(Dcat.grid.selected);
});
JS;

    }

    public function html()
    {
        $id = $this->getKey();

        // 获取当前行数据的用户名
        $name = $this->row->name;

        // 这里需要添加一个class, 和上面script方法对应
        $this->setHtmlAttribute(['data-id' => $id, 'name' => $name, 'class' => 'reduce-count-'.$id]);
        return parent::html(); // TODO: Change the autogenerated stub
    }

}